name: Prettier CI

on:
    pull_request:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  persist-credentials: false

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  dry: true
                  prettier_options: --check .
